// <auto-generated />
using System;
using GridironHQv1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GridironHQv1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230216215503_InitPlayers")]
    partial class InitPlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("GridironHQv1.Entities.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AverageDraftPosition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("College")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentTeam")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("DeclaredInactive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepthDisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepthOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepthPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepthPositionCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftKingsName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DraftKingsPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExperienceString")
                        .HasColumnType("TEXT");

                    b.Property<string>("FanDuelName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FanDuelPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FantasyAlarmPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FantasyDraftName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FantasyDraftPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FantasyPosition")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FantasyPositionDepthOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GlobalTeamID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Height")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeightFeet")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeightInches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InjuryBodyPart")
                        .HasColumnType("TEXT");

                    b.Property<string>("InjuryNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("InjuryPractice")
                        .HasColumnType("TEXT");

                    b.Property<string>("InjuryPracticeDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InjuryStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InjuryStatus")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUndraftedFreeAgent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionCategory")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RotoWirePlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RotoworldPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SportRadarPlayerID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SportsDirectPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatsPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpcomingDraftKingsSalary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpcomingFanDuelSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpcomingGameOpponent")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpcomingGameWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpcomingOpponentPositionRank")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpcomingOpponentRank")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpcomingSalary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpcomingYahooSalary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsaTodayHeadshotNoBackgroundUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsaTodayHeadshotNoBackgroundUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsaTodayHeadshotUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsaTodayHeadshotUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsaTodayPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("XmlTeamPlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YahooName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YahooPlayerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerID");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
